site_name: Pace University CS371
site_url: https://aseriy.github.io/paceuniversity-cs371/
theme:
  name: material

nav:
  - Home: index.md
  - Hardware: hardware.md
  - Operating System: operating-system.md
  - Network Mesh: network-mesh.md
  - CockroachDB: cockroachdb.md

